/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

 
public class ContactEditorUI extends javax.swing.JFrame {
    
  ArrayList<RecIntegral> arrInteg = new ArrayList<>();
  private ArrayList<IntegralThread> threadList = new ArrayList<>();
  private javax.swing.Timer timer;
    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI() {
        initComponents();
        
        timer = new javax.swing.Timer(100, new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkThreads();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonResult = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldUpperLimit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRange = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLowerLimit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setForeground(java.awt.Color.orange);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jButtonResult.setBackground(new java.awt.Color(153, 153, 255));
        jButtonResult.setText("Resault");
        jButtonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(153, 153, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldUpperLimit.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setBackground(new java.awt.Color(102, 255, 204));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Step");

        jTextFieldRange.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lower limit");

        jTextFieldLowerLimit.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setBackground(new java.awt.Color(51, 255, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Upper limit");

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lower Limit", "Upper Limit", "Range", "Resault"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setBackground(new java.awt.Color(102, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cos(x)");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Collection");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Save .txt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setText("Save .binary");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setText("Load .txt");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setText("Load .binary");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldRange, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jButtonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(268, 268, 268))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResult)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setRowCount(0); // Восстанавливаем таблицу из списка объектов

        for (RecIntegral item : arrInteg) {

            tModel.addRow(new Object[] {item.getLowerLimit(), item.getUpperLimit(), item.getRange(), item.getResult()});
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setRowCount(0); // Очистка таблицы
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        double LowerLimit = 0.1;
        double UpperLimit = 1;
        double Range = 0.1;
try{
        LowerLimit = Double.parseDouble(jTextFieldLowerLimit.getText());
        UpperLimit = Double.parseDouble(jTextFieldUpperLimit.getText());
        Range = Double.parseDouble(jTextFieldRange.getText());

       DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

            RecIntegral rec = new RecIntegral(LowerLimit, UpperLimit, Range);
            arrInteg.add(rec);

            tModel.addRow(new Object[] {rec.getLowerLimit(), rec.getUpperLimit(), rec.getRange(), rec.getResult()});
        }catch (InvalidRangeException exe){
            JOptionPane.showMessageDialog(this, 
            exe.getMessage() + "Вы ввели: " + exe.getErrVal(), 
            "Ошибка диапазона", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
            "Введите корректные числа ", 
            "Ошибка ввода", JOptionPane.WARNING_MESSAGE);
        } finally{
        jTextFieldLowerLimit.setText("");
        jTextFieldUpperLimit.setText("");
        jTextFieldRange.setText("");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

        int rowNum = jTable1.getSelectedRow();

        if (rowNum == -1){
            JOptionPane.showMessageDialog(null, "выберите строку");
        }else{
            tModel.removeRow(rowNum);
            arrInteg.remove(rowNum);
           
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
    int rowCount = tModel.getRowCount();
    
    if (rowCount == 0) {
        JOptionPane.showMessageDialog(this,
            "Нет данных для вычисления!\nДобавьте хотя бы одну запись.",
            "Предупреждение", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Очищаем предыдущие потоки (на случай повторного нажатия)
    threadList.clear();
    
    // Блокируем кнопку, чтобы не запустить повторно
    jButtonResult.setEnabled(false);
    
    // Запускаем по одному потоку на каждую строку таблицы (максимум 3)
    int threadsToCreate = Math.min(rowCount, 3);
    
    for (int i = 0; i < threadsToCreate; i++) {
        try {
            double lowerLimit = Double.parseDouble(tModel.getValueAt(i, 0).toString());
            double upperLimit = Double.parseDouble(tModel.getValueAt(i, 1).toString());
            double range = Double.parseDouble(tModel.getValueAt(i, 2).toString());
            
            // Проверка диапазона
            RecIntegral tempRec = new RecIntegral(lowerLimit, upperLimit, range);
            
            IntegralThread thread = new IntegralThread(lowerLimit, upperLimit, range);
            threadList.add(thread);
            thread.start();
            
        } catch (InvalidRangeException exe) {
            JOptionPane.showMessageDialog(this,
                exe.getMessage() + "Вы ввели: " + exe.getErrVal(),
                "Ошибка диапазона", JOptionPane.WARNING_MESSAGE);
            jButtonResult.setEnabled(true);
            return;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Введите корректные числа в строке " + (i + 1),
                "Ошибка ввода", JOptionPane.WARNING_MESSAGE);
            jButtonResult.setEnabled(true);
            return;
        }
    }
    
    // Запускаем таймер для отслеживания завершения
    timer.start();
    
    JOptionPane.showMessageDialog(this,
        "Вычисления запущены в " + threadsToCreate + " потоке(ах).\nДождитесь завершения...",
        "Информация", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonResultActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    if (arrInteg.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Нет данных для сохранения!\nДобавьте хотя бы одну запись.",
            "Предупреждение", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Сохранить в текстовый файл");
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Текстовые файлы (*.txt)", "txt");
    fileChooser.setFileFilter(filter);
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        String path = fileToSave.getAbsolutePath();
        if (!path.toLowerCase().endsWith(".txt")) {
            fileToSave = new File(path + ".txt");
        }
        
        try (PrintWriter writer = new PrintWriter(new FileWriter(fileToSave))) {
            writer.println("Lower Limit | Upper Limit | Range | Result");
            
            for (RecIntegral item : arrInteg) {
                writer.println(item.getLowerLimit() + ";" + 
                              item.getUpperLimit() + ";" + 
                              item.getRange() + ";" + 
                              item.getResult());
            }
            
            JOptionPane.showMessageDialog(this,
                "Данные успешно сохранены в:\n" + fileToSave.getAbsolutePath(),
                "Сохранение выполнено", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Ошибка при сохранении файла:\n" + ex.getMessage(),
                "Ошибка сохранения", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    if (arrInteg.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Нет данных для сохранения!\nДобавьте хотя бы одну запись.",
            "Предупреждение", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Сохранить в двоичный файл");
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Двоичные файлы (*.bin)", "bin");
    fileChooser.setFileFilter(filter);
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        String path = fileToSave.getAbsolutePath();
        if (!path.toLowerCase().endsWith(".bin")) {
            fileToSave = new File(path + ".bin");
        }
        
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileToSave))) {
            oos.writeObject(arrInteg);
            
            JOptionPane.showMessageDialog(this,
                "Данные успешно сохранены в:\n" + fileToSave.getAbsolutePath(),
                "Сохранение выполнено", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Ошибка при сохранении файла:\n" + ex.getMessage(),
                "Ошибка сохранения", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Загрузить из текстового файла");
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Текстовые файлы (*.txt)", "txt");
    fileChooser.setFileFilter(filter);
    
    int userSelection = fileChooser.showOpenDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToOpen = fileChooser.getSelectedFile();
        
        try (BufferedReader reader = new BufferedReader(new FileReader(fileToOpen))) {
            arrInteg.clear();
            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
            tModel.setRowCount(0);
            
            String line;
            boolean isFirstLine = true;
            
            while ((line = reader.readLine()) != null) {
                if (isFirstLine) {
                    isFirstLine = false;
                    continue;
                }
                
                String[] parts = line.split(";");
                if (parts.length == 4) {
                    try {
                        double lowerLimit = Double.parseDouble(parts[0]);
                        double upperLimit = Double.parseDouble(parts[1]);
                        double range = Double.parseDouble(parts[2]);
                        double result = Double.parseDouble(parts[3]);
                        
                        RecIntegral rec = new RecIntegral(lowerLimit, upperLimit, range);
                        rec.setResult(result);
                        arrInteg.add(rec);
                        
                        tModel.addRow(new Object[] {rec.getLowerLimit(), 
                                                   rec.getUpperLimit(), 
                                                   rec.getRange(), 
                                                   rec.getResult()});
                    } catch (NumberFormatException | InvalidRangeException ex) {
                        System.err.println("Пропущена некорректная строка: " + line);
                    }
                }
            }
            
            JOptionPane.showMessageDialog(this,
                "Данные успешно загружены!\nЗагружено записей: " + arrInteg.size(),
                "Загрузка выполнена", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Ошибка при загрузке файла:\n" + ex.getMessage(),
                "Ошибка загрузки", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Загрузить из двоичного файла");
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Двоичные файлы (*.bin)", "bin");
    fileChooser.setFileFilter(filter);
    
    int userSelection = fileChooser.showOpenDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToOpen = fileChooser.getSelectedFile();
        
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileToOpen))) {
            arrInteg.clear();
            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
            tModel.setRowCount(0);
            
            ArrayList<RecIntegral> loadedList = (ArrayList<RecIntegral>) ois.readObject();
            arrInteg.addAll(loadedList);
            
            for (RecIntegral item : arrInteg) {
                tModel.addRow(new Object[] {item.getLowerLimit(), 
                                           item.getUpperLimit(), 
                                           item.getRange(), 
                                           item.getResult()});
            }
            
            JOptionPane.showMessageDialog(this,
                "Данные успешно загружены!\nЗагружено записей: " + arrInteg.size(),
                "Загрузка выполнена", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,
                "Ошибка при загрузке файла:\n" + ex.getMessage(),
                "Ошибка загрузки", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void checkThreads() {
    boolean allDone = true;
    
    for (IntegralThread thread : threadList) {
        if (thread.isAlive()) {
            allDone = false;
            break;
        }
    }
    
    if (allDone && !threadList.isEmpty()) {
        timer.stop();
        
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        
        for (int i = 0; i < threadList.size(); i++) {
            IntegralThread thread = threadList.get(i);
            
            if (thread.isCompleted()) {
                RecIntegral rec = arrInteg.get(i);
                rec.setResult(thread.getResult());
                tModel.setValueAt(thread.getResult(), i, 3);
            } else if (thread.getError() != null) {
                JOptionPane.showMessageDialog(this,
                    "Ошибка в потоке " + (i + 1) + ":\n" + thread.getError().getMessage(),
                    "Ошибка вычисления", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        threadList.clear();
        jButtonResult.setEnabled(true);
        JOptionPane.showMessageDialog(this,
            "Вычисления завершены во всех потоках!",
            "Готово", JOptionPane.INFORMATION_MESSAGE);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLowerLimit;
    private javax.swing.JTextField jTextFieldRange;
    private javax.swing.JTextField jTextFieldUpperLimit;
    // End of variables declaration//GEN-END:variables
}
